### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by marcobonici** [xfangcosmo/FFTLog-and-beyond#1]
Hi @xfangcosmo,
I found the code inside this repo to be really useful and interesting, thanks a lot for sharing it on GitHub.

What do you think about the possibility of creating a pip package to easily install you code for downstream users? I think it would really improve the possibility of spreading the algorithm you have developed. 

If you don't have time, I would be happy to do it myself.

Thank you,
Marco

**Comment by xfangcosmo** [comment]
Hi @marcobonici That's a great idea. Please go ahead creating a pip package - Unfortunately I currently don't have the time, but I'm very happy to help if you have questions/issues with the code.
