### ISSUE TITLE
Typo in cfftlog.c function (?)

### ISSUE THREAD

**Issue by gqcristhian** [xfangcosmo/FFTLog-and-beyond#3]
Hello,

I was updating my code with the newest version of this package and got into troubles. My diagnose is that there is a typo in the function (in cfftlog.c)
void cfftlog()

I think the line
Fy[i] = out_ifft[i-N_pad] * sqrt(M_PI) / (4.*N * pow(y[i], config->nu));
should be rather
Fy[i] = out_ifft[i+N_pad] * sqrt(M_PI) / (4.*N * pow(y[i], config->nu));

When I switch this then I got consistent results to my previous implementation. This - sign is in cfftlog/ and src/

Best regards,
Cristhian Garcia.

**Comment by xfangcosmo** [comment]
Thanks for catching it! Looks like it was introduced when I added N_pad but only tested for cfftlog_ells functions. I fixed them just now.
